name: Dockerfile update with git-auto-commit

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update_dockerfile:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging~=23.1

      - name: Update dockerfile
        run: python update_install-tshark_sh.py >> $GITHUB_STEP_SUMMARY

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update the version of tshark to the latest version."

